### PR TITLE
docs: Fixing errors and patterns

### PR DESCRIPTION
**Pull request by GabrielBarcelos1**
## Summary
- Removing unnecessary React import
- Adding Suspense in parts it was used
- Removing Fragment in parts it wasn't used
- fixing import order so that a pattern is maintained throughout the documentation

Resolve: none issue

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by marcospassos** [comment]
Thank you for your collaboration, @GabrielBarcelos1! Can you remove the `yarn.lock` from your commit? Everything else looks good to me.

**Comment by GabrielBarcelos1** [comment]
It's done 😀

**Review by Fryuni — APPROVED** [review]
LGTM

**Comment by Fryuni** [comment]
@marcospassos I fixed the security checks on master already so I'll merge this 😄

**Comment by marcospassos** [comment]
Thank you, everyone!

**Pull request merged**
